<?php
//variabel super global
$mahasiswa = [
    [
        "nim" => "23.52.0004"
        "nama" => "Fangki"
        "jurusan" => "Teknologi Informasi"
        "email" => "bayu_23520004@stimata.ac.id"
        "gambar" => "23.52.0004"
    ]

    [
        "nama" => "Meta"
        "nim" => "23.52.0005"
        "jurusan" => "Teknologi Informasi"
        "email" => "bayu_23520004@stimata.ac.id"
        "gambar" => "23.52.0004"
    ]
];
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
</html>